name: Chamber Audit Pocs Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  audit-pocs-tests-chamber:
    uses: ./.github/workflows/tests-template.yml
    with:
      make-command: test-audit-pocs-mainnet-fork
    secrets: inherit